package com.gabrieljamesbenedict.SyntaxAnalysis;

public enum NodeType {
    PROGRAM,

    EMPTY_STATEMENT,
    BLOCK_STATEMENT,

    VARIABLE_DECLARATION,
    ARRAY_DECLARATION,
    FUNCTION_DECLARATION,

    // Implement this in the future
    FIXED_MODIFIER,
    STRICT_MODIFIER,

    VARIABLE_NAME,
    VARIABLE_TYPE,
    VARIABLE_BODY,

    ARRAY_NAME,
    ARRAY_SIZE,
    ARRAY_ELEMENT,
    ARRAY_ELEMENT_TYPE,
    ARRAY_BODY,

    FUNCTION_NAME,
    FUNCTION_PARAMETERS,
    FUNCTION_PARAMETER,
    FUNCTION_PARAMETER_NAME,
    FUNCTION_PARAMETER_TYPE,
    FUNCTION_RETURN_TYPE,
    FUNCTION_BODY,
    FUNCTION_ARGUMENTS,
    FUNCTION_ARGUMENT,
    FUNCTION_ARGUMENT_NAME,
    FUNCTION_ARGUMENT_TYPE,

    RETURN_STATEMENT,
    NO_RETURN,


    CONDITIONAL,
    IF,
    IF_CONDITION,
    IF_BODY,
    ELSE_IF,
    ELSE_IF_CONDITION,
    ELSE_IF_BODY,
    ELSE,
    ELSE_BODY,

    SWITCH,
    SWITCH_EXPRESSION,
    CASES,
    CASE,
    CASE_EXPRESSION,
    CASE_BODY,
    DEFAULT,
    DEFAULT_BODY,

    LOOP,
    LOOP_CONDITION,
    LOOP_BODY,
    WHILE, DO_WHILE,
    UNTIL, DO_UNTIL,
    FOR, FOR_VARIABLE, FOR_ARRAY,
    REPEAT, REPEAT_AMOUNT,
    REPEAT_VARIABLE, REPEAT_VARIABLE_NAME, REPEAT_VARIABLE_START,

    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    MODULO,
    PRE_INCREMENT,
    PRE_DECREMENT,
    POST_INCREMENT,
    POST_DECREMENT,
    NEGATIVE,

    ASSIGNMENT,
    ADDITION_ASSIGNMENT,
    SUBTRACTION_ASSIGNMENT,
    MULTIPLICATION_ASSIGNMENT,
    DIVISION_ASSIGNMENT,
    MODULO_ASSIGNMENT,

    NOT,
    OR,
    NOR,
    XOR,
    XNOR,
    AND,
    NAND,
    EQUALS,
    NOTEQUALS,
    LESS,
    LESSEQUALS,
    GREATER,
    GREATEREQUALS,


    TYPE_INT,
    TYPE_FLOAT,
    TYPE_CHAR,
    TYPE_STRING,
    TYPE_BOOLEAN,

    LITERAL_INT,
    LITERAL_FLOAT,
    LITERAL_CHAR,
    LITERAL_STRING,
    LITERAL_TRUE,
    LITERAL_FALSE,
    LITERAL_ARRAY,

    EOF

}
