package com.gabrieljamesbenedict.SyntaxAnalysis.node;

public enum NodeType {
    PROGRAM,

    EMPTY_STATEMENT,
    BLOCK_STATEMENT,

    VARIABLE_DECLARATION,

    VARIABLE_TYPE,

    IDENTIFIER,
    VARIABLE_IDENTIFIER,
    ARRAY_IDENTIFIER,

    CONDITIONAL,
    IF,
    ELSE,
    ELSE_IF,

    SWITCH,
    CASE,
    DEFAULT,

    WHILE_LOOP,
    DO_WHILE_LOOP,
    UNTIL_LOOP,
    DO_UNTIL_LOOP,
    FOR_LOOP,
    REPEAT_LOOP,

    REPEAT_AMOUNT,

    BINARY_EXPRESSION,
    UNARY_EXPRESSION,

    FUNCTION_EXPRESSION,

    ADDITION,
    SUBTRACTION,
    MULTIPLICATION,
    DIVISION,
    MODULO,
    PRE_INCREMENT,
    PRE_DECREMENT,
    POST_INCREMENT,
    POST_DECREMENT,
    NEGATIVE,

    ASSIGNMENT,
    ADDITION_ASSIGNMENT,
    SUBTRACTION_ASSIGNMENT,
    MULTIPLICATION_ASSIGNMENT,
    DIVISION_ASSIGNMENT,
    MODULO_ASSIGNMENT,

    TYPE_INT,
    TYPE_FLOAT,
    TYPE_CHAR,
    TYPE_STRING,
    TYPE_BOOLEAN,

    LITERAL_INT,
    LITERAL_FLOAT,
    LITERAL_CHAR,
    LITERAL_STRING,
    LITERAL_TRUE,
    LITERAL_FALSE,
    LITERAL_ARRAY,

    EOF

}
